// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// glm_NR
Eigen::VectorXd glm_NR(Eigen::VectorXd y, Eigen::VectorXd nn, Eigen::MatrixXd X, std::string family, double a);
RcppExport SEXP _GLMGEX_glm_NR(SEXP ySEXP, SEXP nnSEXP, SEXP XSEXP, SEXP familySEXP, SEXP aSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
  Rcpp::traits::input_parameter< Eigen::VectorXd >::type nn(nnSEXP);
  Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
  Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
  Rcpp::traits::input_parameter< double >::type a(aSEXP);
  rcpp_result_gen = Rcpp::wrap(glm_NR(y, nn, X, family, a));
  return rcpp_result_gen;
  END_RCPP
}
// Ca_Mu
Eigen::VectorXd Ca_Mu(Eigen::VectorXd y, Eigen::VectorXd nn, Eigen::MatrixXd X, std::string family, Eigen::VectorXd beta);
RcppExport SEXP _GLMGEX_Ca_Mu(SEXP ySEXP, SEXP nnSEXP, SEXP XSEXP, SEXP familySEXP, SEXP betaSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
  Rcpp::traits::input_parameter< Eigen::VectorXd >::type nn(nnSEXP);
  Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
  Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
  Rcpp::traits::input_parameter< Eigen::VectorXd >::type beta(betaSEXP);
  rcpp_result_gen = Rcpp::wrap(Ca_Mu(y, nn, X, family, beta));
  return rcpp_result_gen;
  END_RCPP
}
// Ca_Wii
Eigen::VectorXd Ca_Wii(Eigen::VectorXd y, Eigen::VectorXd nn, std::string family, Eigen::VectorXd mu, Eigen::VectorXd beta, double a);
RcppExport SEXP _GLMGEX_Ca_Wii(SEXP ySEXP, SEXP nnSEXP, SEXP familySEXP, SEXP muSEXP, SEXP betaSEXP, SEXP aSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
  Rcpp::traits::input_parameter< Eigen::VectorXd >::type nn(nnSEXP);
  Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
  Rcpp::traits::input_parameter< Eigen::VectorXd >::type mu(muSEXP);
  Rcpp::traits::input_parameter< Eigen::VectorXd >::type beta(betaSEXP);
  Rcpp::traits::input_parameter< double >::type a(aSEXP);
  rcpp_result_gen = Rcpp::wrap(Ca_Wii(y, nn, family, mu, beta, a));
  return rcpp_result_gen;
  END_RCPP
}
// generateSubmatrix
Eigen::MatrixXd generateSubmatrix(const Eigen::MatrixXd& X, int envir);
RcppExport SEXP _GLMGEX_generateSubmatrix(SEXP XSEXP, SEXP envirSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
  Rcpp::traits::input_parameter< int >::type envir(envirSEXP);
  rcpp_result_gen = Rcpp::wrap(generateSubmatrix(X, envir));
  return rcpp_result_gen;
  END_RCPP
}
// forward_selection
Eigen::VectorXi forward_selection(const Eigen::VectorXd& y, const Eigen::VectorXd& nn, const Eigen::MatrixXd& X, const Eigen::MatrixXd& G, const std::string& family, int envir, double threshold, double a, Eigen::VectorXi& x_indices, Eigen::VectorXi& y_indices);
RcppExport SEXP _GLMGEX_forward_selection(SEXP ySEXP, SEXP nnSEXP, SEXP XSEXP, SEXP GSEXP, SEXP familySEXP, SEXP envirSEXP, SEXP thresholdSEXP, SEXP aSEXP, SEXP x_indicesSEXP, SEXP y_indicesSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
  Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type nn(nnSEXP);
  Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
  Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type G(GSEXP);
  Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
  Rcpp::traits::input_parameter< int >::type envir(envirSEXP);
  Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
  Rcpp::traits::input_parameter< double >::type a(aSEXP);
  Rcpp::traits::input_parameter< Eigen::VectorXi& >::type x_indices(x_indicesSEXP);
  Rcpp::traits::input_parameter< Eigen::VectorXi& >::type y_indices(y_indicesSEXP);
  rcpp_result_gen = Rcpp::wrap(forward_selection(y, nn, X, G, family, envir, threshold, a, x_indices, y_indices));
  return rcpp_result_gen;
  END_RCPP
}
// score_test
List score_test(Eigen::VectorXd y, Eigen::VectorXd mu, Eigen::VectorXd Wii, Eigen::MatrixXd G, Eigen::MatrixXd proj, Eigen::VectorXd beta, const std::string family, int envir, double b, double a, bool epistasis_test, bool parallel);
RcppExport SEXP _GLMGEX_score_test(SEXP ySEXP, SEXP muSEXP, SEXP WiiSEXP, SEXP GSEXP, SEXP projSEXP, SEXP betaSEXP, SEXP familySEXP, SEXP envirSEXP, SEXP bSEXP, SEXP aSEXP, SEXP epistasis_testSEXP, SEXP parallelSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
  Rcpp::traits::input_parameter< Eigen::VectorXd >::type mu(muSEXP);
  Rcpp::traits::input_parameter< Eigen::VectorXd >::type Wii(WiiSEXP);
  Rcpp::traits::input_parameter< Eigen::MatrixXd >::type G(GSEXP);
  Rcpp::traits::input_parameter< Eigen::MatrixXd >::type proj(projSEXP);
  Rcpp::traits::input_parameter< Eigen::VectorXd >::type beta(betaSEXP);
  Rcpp::traits::input_parameter< const std::string >::type family(familySEXP);
  Rcpp::traits::input_parameter< int >::type envir(envirSEXP);
  Rcpp::traits::input_parameter< double >::type b(bSEXP);
  Rcpp::traits::input_parameter< double >::type a(aSEXP);
  Rcpp::traits::input_parameter< bool >::type epistasis_test(epistasis_testSEXP);
  Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
  rcpp_result_gen = Rcpp::wrap(score_test(y, mu, Wii, G, proj, beta, family, envir, b, a, epistasis_test, parallel));
  return rcpp_result_gen;
  END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
  {"_GLMGEX_glm_NR", (DL_FUNC) &_GLMGEX_glm_NR, 5},
  {"_GLMGEX_Ca_Mu", (DL_FUNC) &_GLMGEX_Ca_Mu, 5},
  {"_GLMGEX_Ca_Wii", (DL_FUNC) &_GLMGEX_Ca_Wii, 6},
  {"_GLMGEX_generateSubmatrix", (DL_FUNC) &_GLMGEX_generateSubmatrix, 2},
  {"_GLMGEX_forward_selection", (DL_FUNC) &_GLMGEX_forward_selection, 10},
  {"_GLMGEX_score_test", (DL_FUNC) &_GLMGEX_score_test, 12},
  {NULL, NULL, 0}
};

RcppExport void R_init_GLMGEX(DllInfo *dll) {
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
